# Generated by Django 3.1.1 on 2020-09-19 05:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200913_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
