# Generated by Django 3.1.1 on 2020-09-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200919_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_added',
        ),
    ]
