# Generated by Django 3.0.7 on 2020-08-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200815_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website_url',
            new_name='website_url',
        ),
    ]
