# Generated by Django 3.0.7 on 2020-08-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200816_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
